#!/bin/sh
# this script tries to discover the OS platform and configuration
# and then makes newLISP using the appropiate makefile
# if this script fails and for other special flavors, like
# making shared libraries etc., type: 
#
#      make help
# to see all options
#

echo
case `uname` in 
	Darwin)
		echo Discovered Darwin Mac OSX with readline suport:
		if [ -e /usr/lib/libreadline.dylib ]; then
			make darwin_utf8 # make with readline support
		else 
			make osx # make without readline support
		fi
		exit
		;;
	Linux)
		echo Discovered Linux:
		make linux
		exit
		;;
	FreeBSD)
		echo Discovered FreeBSD:
		make bsd
		exit
		;;
	NetBSD)
		echo Discovered NetBSD:
		make netbsd
		exit
		;;
	OpenBSD)
		echo Discoverd OpenBSD:
		make bsd
		exit
		;;
	SunOS)
		echo  Discovered SunOS:
		make solaris
		exit
		;;
	OSF1)
		echo Discovered Tru64 Unix, please read doc/TRU64BUILD
		make -f makefile_tru64
		exit
		;;
MINGW32_NT-5.1)
		echo Discoverd MINGW32 on NT-5.1
		make mingw	# this is with MinGW on MSYS
		exit
		;;
	OS/2)
		echo Discoverd OS/2
		make os2
		exit
		;;
esac

echo Could not discover your OS platform use one of the following commands:

make help
