#!/bin/sh
# this script tries to discover the OS platform and configuration
# and then makes newLISP using the appropiate makefile
# if this script fails and for other special flavors, like
# making shared libraries etc., type: 
#
#      make help
# to see all options
#
# this is similar too configure, which only discovers the platform,
# but also builds.

echo
case `uname` in 
	Darwin)
		echo Discovered Darwin Mac OSX with readline suport:
		if [ -e /usr/lib/libreadline.dylib ]; then
			make darwin_utf8 # make with readline support
		else 
			make darwin # make without readline support
		fi
		exit
		;;
	Linux)
		echo Discovered Linux:
		make linux_utf8
		exit
		;;
	FreeBSD)
		echo Discovered FreeBSD:
		make bsd_utf8
		exit
		;;
	NetBSD)
		echo Discovered NetBSD:
		make netbsd_utf8
		exit
		;;
	OpenBSD)
		echo Discoverd OpenBSD:
		make bsd_utf8
		exit
		;;
	SunOS)
		echo  Discovered SunOS, making for Sparc CPU:
		make sunos
		exit
		;;
	AIX) 
		echo  Discovered AIX: 
		gmake aix64
		exit 
		;; 
	OSF1)
		echo Discovered Tru64 Unix, please read doc/TRU64BUILD
		make -f makefile_tru64
		exit
		;;
MINGW32_NT-5.1)
		echo Discoverd MINGW32 on NT-5.1
		make mingw	# this is with MinGW on MSYS
		exit
		;;
	OS/2)
		echo Discoverd OS/2
		make os2
		exit
		;;
esac

echo Could not discover your OS platform use one of the following commands:

make help
