#ifndef VERSION_H
#define VERSION_H

#define NEWLISP_SOFTWARE_NAME "newLISP"

#define NEWLISP_COPYRIGHT "Copyright (C) 2016 Lutz Muller"

#define NEWLISP_VERSION "10.7.0"

#define NEWLISP_VERSION_MAJOR 10
#define NEWLISP_VERSION_MINOR  7
#define NEWLISP_VERSION_PATCH  0

#define NEWLISP_VERSION_NUM 10700

#endif  /* VERSION_H */
