#!/bin/sh
# this script tries to discover the OS platform and configuration
# and then makes newLISP using the appropiate makefile
# if this script fails and for other special flavors, like
# making shared libraries etc., type: 
#
#      make help
# to see all options
#
# this is similar too configure, which only discovers the platform,
# but also builds.

echo
if [ -f makefile_configure -a -f config.h ] ; then
	if grep AIX config.h ; then
		gmake -f makefile_configure;
	else
		make -f makefile_configure;
	fi
else

echo Could not discover your OS platform use one of the following commands:
make help

fi
